apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{ values.vmName }}
  namespace: rhdh-demo
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
        resources:
          requests:
            memory: ${{ values.memory }}Gi
        cpu:
          cores: ${{ values.cores }}
      volumes:
        - name: containerdisk
          containerDisk:
            image: registry.redhat.io/rhel9/rhel-guest-image:latest
